CommitMsg:
  SpellCheck:
    enabled: true
    on_warn: fail
    skip_if: ['bash', '-c', '! which hunspell']

PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail
  TravisLint:
    enabled: true
    on_warn: fail

PrePush:
  RSpec:
    enabled: true
    on_warn: fail
