require: rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/spec_helper.rb'

Layout/LineLength:
  Max: 100

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
