# frozen_string_literal: true

source 'https://rubygems.org'

group :development do
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'overcommit'
  gem 'rubocop'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
end

group :test do
  gem 'rspec'
  gem 'simplecov'
end

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
  gem 'rake'
end
