require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: '{{cookiecutter.required_ruby_version}}'

Metrics/BlockLength:
  Exclude:
    - 'spec/spec_helper.rb'

Naming/FileName:
  Exclude:
    - 'lib/{{cookiecutter.project_kebab}}.rb'

Layout/LineLength:
  Max: 120

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
