# frozen_string_literal: true

ruby '>= {{cookiecutter.required_ruby_version}}'
source 'https://rubygems.org'
gemspec

gem 'guard-rspec'
gem 'guard-rubocop'
gem 'overcommit'
gem 'pry'
gem 'pry-byebug'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'simplecov'
gem 'solargraph'
gem 'travis'
